#!/bin/bash
# Script para desplegar fácilmente

echo "==================================="
echo "🚀 Aplicación Edenred - Despliegue"
echo "==================================="
echo ""
echo "Archivos generados en: dist/"
echo "Tamaño: ~9KB CSS + 154KB JS"
echo ""
echo "✅ OPCIÓN 1: Vercel (RECOMENDADO)"
echo "   URL: https://vercel.com"
echo "   1. git push a GitHub"
echo "   2. Importar en Vercel"
echo "   3. ¡Listo en segundos!"
echo ""
echo "✅ OPCIÓN 2: Netlify"
echo "   URL: https://netlify.com"
echo "   1. git push a GitHub"
echo "   2. Importar en Netlify"
echo "   3. ¡Listo en minutos!"
echo ""
echo "✅ OPCIÓN 3: Servidor Local"
echo "   npm install -g http-server"
echo "   cd dist && http-server -p 8080"
echo "   Acceder: http://localhost:8080"
echo ""
echo "Más detalles en: DEPLOYMENT.md"
echo "==================================="
